### ISSUE TITLE
uninitialized constant Permissions 

### ISSUE THREAD

**Issue by trisignia** [makandra/aegis#9]
Any idea why I'd get this error in development after successfully running functional tests against my app's Aegis/Clearance authentication and access-control scheme?  Could this have something to do with me running my app w/Phusion Passenger?

Here's the full trace:

```
vendor/rails/activesupport/lib/active_support/dependencies.rb:443:in `load_missing_constant'
vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in `const_missing'
vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in `const_missing'
vendor/rails/activesupport/lib/active_support/inflector.rb:361:in `constantize'
vendor/rails/activesupport/lib/active_support/inflector.rb:360:in `each'
vendor/rails/activesupport/lib/active_support/inflector.rb:360:in `constantize'
vendor/rails/activesupport/lib/active_support/core_ext/string/inflections.rb:162:in `constantize'
vendor/gems/aegis-2.4.1/lib/aegis/permissions.rb:95:in `app_permissions'
vendor/gems/aegis-2.4.1/lib/aegis/has_role.rb:6:in `has_role'
vendor/gems/aegis-2.4.1/lib/aegis/has_role.rb:71:in `call'
vendor/gems/aegis-2.4.1/lib/aegis/has_role.rb:71:in `method_missing_with_aegis_permissions'
app/controllers/offers_controller.rb:26:in `method_missing'
app/controllers/offers_controller.rb:26:in `new'
```

Thank you in advance for your help,

Jacob

**Comment by trisignia** [comment]
I've just confirmed that I can run the app using Mongrel, so it must be an issue with running Aegis in conjunction with Passenger.

Have you guys come across this error before?

**Comment by trisignia** [comment]
Hmm, never mind.  I had to re-boot the app, which I swear I did earlier, but... ;-)

Thanks for a very handy and lightweight role-based access system.
